#lang racket

(require "types.rkt"
         (only-in "private/check-runtime.rkt"
                  named-value?
                  named-value-name
                  named-value-value
                  named-value-facts
                  named-value-bindings
                  check-ok?
                  check-ok-value
                  check-ok-facts
                  check-ok-bindings
                  check-fail?
                  check-fail-message
                  check-fail-status
                  check-fail-details
                  detached-proof?
                  detached-proof-fact
                  detached-proof-bindings
                  packed-witness?
                  packed-witness-public-name
                  packed-witness-value
                  packed-exists?
                  packed-exists-witnesses
                  packed-exists-body
                  runtime-binding?
                  runtime-binding-name
                  runtime-binding-raw
                  runtime-binding-bindings
                  check-result?
                  check-success?
                  raw-value
                  tesl-display-val
                  forget-proof
                  instantiate-proof-template
                  facts-of
                  ensure-named
                  attach-proof
                  accept/value
                  detach-proof
                  detach-all-proof
                  intro-and
                  and-left
                  and-right
                  pack
                  unpack
                  let-exists
                  define-checker
                  define-auther
                  accept
                  reject
                  let/check
                  if/check
                  check-and))

(provide
 (all-from-out "types.rkt")
 named-value?
 named-value-name
 named-value-value
 named-value-facts
 named-value-bindings
 check-ok?
 check-ok-value
 check-ok-facts
 check-ok-bindings
 check-fail?
 check-fail-message
 check-fail-status
 check-fail-details
 detached-proof?
 detached-proof-fact
 detached-proof-bindings
 packed-witness?
 packed-witness-public-name
 packed-witness-value
 packed-exists?
 packed-exists-witnesses
 packed-exists-body
 runtime-binding?
 runtime-binding-name
 runtime-binding-raw
 runtime-binding-bindings
 check-result?
 check-success?
 raw-value
 tesl-display-val
 instantiate-proof-template
 facts-of
 forget-proof
 ensure-named
 attach-proof
 detach-proof
 detach-all-proof
 intro-and
 and-left
 and-right
 pack
 unpack
 let-exists
 define-checker
 define-auther
 accept
 accept/value
 reject
 let/check
 if/check
 check-and)

