package teslrt

import (
	"fmt"
)

// Property tests: `property "name" (n: Int) { … }` inside a `test` block, run many times over
// generated values.
//
// The generators are `dsl/test-support.rkt`'s, value for value, because a property that holds
// on one backend and fails on the other would otherwise be a difference in what was GENERATED
// rather than in what the program does:
//
//	Int      uniform in [-1_000_000, 1_000_000]
//	Bool     a coin flip
//	String   "s" followed by a number below 1_000_000 — short, printable, and never empty
//	List T   0 to 7 elements, each generated by T's own generator
//	Maybe T  Nothing or Something, evenly
//
// A type with no generator is REFUSED at emission rather than generated as a zero: Racket's
// fallback produces `0` for anything it does not know, and a property that "passes" over 200
// copies of the same wrong-typed value tests nothing at all.
//
// Randomness is unseeded, as Racket's is: a property test is a search for a counterexample,
// not a fixture, and the same seed every run would search the same 200 points forever. The
// source is `crypto/rand` through `RandomInt`, for the reason the rest of this runtime uses it
// — no Tesl surface can seed a generator, so there is nothing to gain from a weak one, and
// gosec flags math/rand wherever it appears.

// PropRandom is Racket's `tesl-prop-random`: a value in [0, bound). It is also what a custom
// generator receives its variety from.
func PropRandom(bound Int) Int {
	if Compare(bound, FromInt64(1)) < 0 {
		panic("property generator: bound must be a positive Int, got " + bound.String())
	}
	return RandomInt(FromInt64(0), bound)
}

// PropInt generates a signed value around zero, so a property meets negatives, zero and
// positives rather than only the happy side.
func PropInt() Int {
	return RandomInt(FromInt64(-1_000_000), FromInt64(1_000_001))
}

func PropBool() bool {
	return Compare(RandomInt(FromInt64(0), FromInt64(2)), FromInt64(0)) == 0
}

func PropString() string {
	return fmt.Sprintf("s%s", RandomInt(FromInt64(0), FromInt64(1_000_000)).String())
}

// PropList generates 0 to 7 elements — the empty list included, since that is the case a
// property over a list most often gets wrong.
func PropList[Element any](element func() Element) []Element {
	count, _ := RandomInt(FromInt64(0), FromInt64(8)).Int64()
	out := make([]Element, count)
	for index := range out {
		out[index] = element()
	}
	return out
}

func PropMaybe[Element any](element func() Element) Maybe[Element] {
	if Compare(RandomInt(FromInt64(0), FromInt64(2)), FromInt64(0)) == 0 {
		return Nothing[Element]()
	}
	return Something(element())
}
