package teslrt

// Generated by scripts/gen-go-units.py from tesl/units.rkt.
// DO NOT EDIT BY HAND — regenerate and commit when a conversion factor changes.
//
// A dimensioned quantity ERASES to a plain float64: the dimension lives in the
// compiler's type layer, so every function here is ordinary arithmetic. A CONSTRUCTOR
// converts a value in the named unit to the SI-canonical magnitude (meters, kilograms,
// seconds, …); an ACCESSOR converts back. The factors are the Racket runtime's, read
// from the file that owns them.

func LengthMeters(value float64) float64                            { return value * 1.0 }
func LengthKilometers(value float64) float64                        { return value * 1000.0 }
func LengthCentimeters(value float64) float64                       { return value * 0.01 }
func LengthMillimeters(value float64) float64                       { return value * 0.001 }
func LengthMiles(value float64) float64                             { return value * 1609.344 }
func LengthFeet(value float64) float64                              { return value * 0.3048 }
func LengthInches(value float64) float64                            { return value * 0.0254 }
func LengthYards(value float64) float64                             { return value * 0.9144 }
func LengthNauticalMiles(value float64) float64                     { return value * 1852.0 }
func LengthInMeters(quantity float64) float64                       { return quantity / 1.0 }
func LengthInKilometers(quantity float64) float64                   { return quantity / 1000.0 }
func LengthInCentimeters(quantity float64) float64                  { return quantity / 0.01 }
func LengthInMillimeters(quantity float64) float64                  { return quantity / 0.001 }
func LengthInMiles(quantity float64) float64                        { return quantity / 1609.344 }
func LengthInFeet(quantity float64) float64                         { return quantity / 0.3048 }
func LengthInInches(quantity float64) float64                       { return quantity / 0.0254 }
func LengthInYards(quantity float64) float64                        { return quantity / 0.9144 }
func LengthInNauticalMiles(quantity float64) float64                { return quantity / 1852.0 }
func MassKilograms(value float64) float64                           { return value * 1.0 }
func MassGrams(value float64) float64                               { return value * 0.001 }
func MassMilligrams(value float64) float64                          { return value * 0.000001 }
func MassTonnes(value float64) float64                              { return value * 1000.0 }
func MassPounds(value float64) float64                              { return value * 0.45359237 }
func MassOunces(value float64) float64                              { return value * 0.028349523125 }
func MassInKilograms(quantity float64) float64                      { return quantity / 1.0 }
func MassInGrams(quantity float64) float64                          { return quantity / 0.001 }
func MassInMilligrams(quantity float64) float64                     { return quantity / 0.000001 }
func MassInTonnes(quantity float64) float64                         { return quantity / 1000.0 }
func MassInPounds(quantity float64) float64                         { return quantity / 0.45359237 }
func MassInOunces(quantity float64) float64                         { return quantity / 0.028349523125 }
func DurationSeconds(value float64) float64                         { return value * 1.0 }
func DurationMilliseconds(value float64) float64                    { return value * 0.001 }
func DurationMinutes(value float64) float64                         { return value * 60.0 }
func DurationHours(value float64) float64                           { return value * 3600.0 }
func DurationDays(value float64) float64                            { return value * 86400.0 }
func DurationInSeconds(quantity float64) float64                    { return quantity / 1.0 }
func DurationInMilliseconds(quantity float64) float64               { return quantity / 0.001 }
func DurationInMinutes(quantity float64) float64                    { return quantity / 60.0 }
func DurationInHours(quantity float64) float64                      { return quantity / 3600.0 }
func DurationInDays(quantity float64) float64                       { return quantity / 86400.0 }
func SpeedMetersPerSecond(value float64) float64                    { return value * 1.0 }
func SpeedKilometersPerHour(value float64) float64                  { return value * 0.2777777777777778 }
func SpeedMilesPerHour(value float64) float64                       { return value * 0.44704 }
func SpeedKnots(value float64) float64                              { return value * 0.5144444444444445 }
func SpeedInMetersPerSecond(quantity float64) float64               { return quantity / 1.0 }
func SpeedInKilometersPerHour(quantity float64) float64             { return quantity / 0.2777777777777778 }
func SpeedInMilesPerHour(quantity float64) float64                  { return quantity / 0.44704 }
func SpeedInKnots(quantity float64) float64                         { return quantity / 0.5144444444444445 }
func AccelerationMetersPerSecondSquared(value float64) float64      { return value * 1.0 }
func AccelerationInMetersPerSecondSquared(quantity float64) float64 { return quantity / 1.0 }
func AreaSquareMeters(value float64) float64                        { return value * 1.0 }
func AreaSquareKilometers(value float64) float64                    { return value * 1000000.0 }
func AreaHectares(value float64) float64                            { return value * 10000.0 }
func AreaSquareFeet(value float64) float64                          { return value * 0.09290304 }
func AreaAcres(value float64) float64                               { return value * 4046.8564224 }
func AreaInSquareMeters(quantity float64) float64                   { return quantity / 1.0 }
func AreaInSquareKilometers(quantity float64) float64               { return quantity / 1000000.0 }
func AreaInHectares(quantity float64) float64                       { return quantity / 10000.0 }
func AreaInSquareFeet(quantity float64) float64                     { return quantity / 0.09290304 }
func AreaInAcres(quantity float64) float64                          { return quantity / 4046.8564224 }
func VolumeCubicMeters(value float64) float64                       { return value * 1.0 }
func VolumeLiters(value float64) float64                            { return value * 0.001 }
func VolumeMilliliters(value float64) float64                       { return value * 0.000001 }
func VolumeGallons(value float64) float64                           { return value * 0.003785411784 }
func VolumeInCubicMeters(quantity float64) float64                  { return quantity / 1.0 }
func VolumeInLiters(quantity float64) float64                       { return quantity / 0.001 }
func VolumeInMilliliters(quantity float64) float64                  { return quantity / 0.000001 }
func VolumeInGallons(quantity float64) float64                      { return quantity / 0.003785411784 }
func ForceNewtons(value float64) float64                            { return value * 1.0 }
func ForceInNewtons(quantity float64) float64                       { return quantity / 1.0 }
func EnergyJoules(value float64) float64                            { return value * 1.0 }
func EnergyKilojoules(value float64) float64                        { return value * 1000.0 }
func EnergyKilowattHours(value float64) float64                     { return value * 3600000.0 }
func EnergyCalories(value float64) float64                          { return value * 4.184 }
func EnergyInJoules(quantity float64) float64                       { return quantity / 1.0 }
func EnergyInKilojoules(quantity float64) float64                   { return quantity / 1000.0 }
func EnergyInKilowattHours(quantity float64) float64                { return quantity / 3600000.0 }
func EnergyInCalories(quantity float64) float64                     { return quantity / 4.184 }
func PowerWatts(value float64) float64                              { return value * 1.0 }
func PowerKilowatts(value float64) float64                          { return value * 1000.0 }
func PowerHorsepower(value float64) float64                         { return value * 745.6998715822702 }
func PowerInWatts(quantity float64) float64                         { return quantity / 1.0 }
func PowerInKilowatts(quantity float64) float64                     { return quantity / 1000.0 }
func PowerInHorsepower(quantity float64) float64                    { return quantity / 745.6998715822702 }
func FrequencyHertz(value float64) float64                          { return value * 1.0 }
func FrequencyKilohertz(value float64) float64                      { return value * 1000.0 }
func FrequencyInHertz(quantity float64) float64                     { return quantity / 1.0 }
func FrequencyInKilohertz(quantity float64) float64                 { return quantity / 1000.0 }
func PressurePascals(value float64) float64                         { return value * 1.0 }
func PressureKilopascals(value float64) float64                     { return value * 1000.0 }
func PressureBar(value float64) float64                             { return value * 100000.0 }
func PressureInPascals(quantity float64) float64                    { return quantity / 1.0 }
func PressureInKilopascals(quantity float64) float64                { return quantity / 1000.0 }
func PressureInBar(quantity float64) float64                        { return quantity / 100000.0 }
