(* Generated by scripts/gen-currencies.py from the ISO 4217 active list.
   DO NOT EDIT BY HAND — regenerate and commit when ISO 4217 changes.
   155 currencies.  minor_digits is load-bearing (rounding,
   Money.display): USD=2, JPY=0, BHD=3. *)

(** (constructor, iso_code, numeric_code, minor_digits) — the fixed
    `Currency` set. *)
let currencies : (string * string * int * int) list = [
  ("Aed", "AED", 784, 2);
  ("Afn", "AFN", 971, 2);
  ("All", "ALL", 8, 2);
  ("Amd", "AMD", 51, 2);
  ("Ang", "ANG", 532, 2);
  ("Aoa", "AOA", 973, 2);
  ("Ars", "ARS", 32, 2);
  ("Aud", "AUD", 36, 2);
  ("Awg", "AWG", 533, 2);
  ("Azn", "AZN", 944, 2);
  ("Bam", "BAM", 977, 2);
  ("Bbd", "BBD", 52, 2);
  ("Bdt", "BDT", 50, 2);
  ("Bgn", "BGN", 975, 2);
  ("Bhd", "BHD", 48, 3);
  ("Bif", "BIF", 108, 0);
  ("Bmd", "BMD", 60, 2);
  ("Bnd", "BND", 96, 2);
  ("Bob", "BOB", 68, 2);
  ("Brl", "BRL", 986, 2);
  ("Bsd", "BSD", 44, 2);
  ("Btn", "BTN", 64, 2);
  ("Bwp", "BWP", 72, 2);
  ("Byn", "BYN", 933, 2);
  ("Bzd", "BZD", 84, 2);
  ("Cad", "CAD", 124, 2);
  ("Cdf", "CDF", 976, 2);
  ("Chf", "CHF", 756, 2);
  ("Clp", "CLP", 152, 0);
  ("Cny", "CNY", 156, 2);
  ("Cop", "COP", 170, 2);
  ("Crc", "CRC", 188, 2);
  ("Cup", "CUP", 192, 2);
  ("Cve", "CVE", 132, 2);
  ("Czk", "CZK", 203, 2);
  ("Djf", "DJF", 262, 0);
  ("Dkk", "DKK", 208, 2);
  ("Dop", "DOP", 214, 2);
  ("Dzd", "DZD", 12, 2);
  ("Egp", "EGP", 818, 2);
  ("Ern", "ERN", 232, 2);
  ("Etb", "ETB", 230, 2);
  ("Eur", "EUR", 978, 2);
  ("Fjd", "FJD", 242, 2);
  ("Fkp", "FKP", 238, 2);
  ("Gbp", "GBP", 826, 2);
  ("Gel", "GEL", 981, 2);
  ("Ghs", "GHS", 936, 2);
  ("Gip", "GIP", 292, 2);
  ("Gmd", "GMD", 270, 2);
  ("Gnf", "GNF", 324, 0);
  ("Gtq", "GTQ", 320, 2);
  ("Gyd", "GYD", 328, 2);
  ("Hkd", "HKD", 344, 2);
  ("Hnl", "HNL", 340, 2);
  ("Htg", "HTG", 332, 2);
  ("Huf", "HUF", 348, 2);
  ("Idr", "IDR", 360, 2);
  ("Ils", "ILS", 376, 2);
  ("Inr", "INR", 356, 2);
  ("Iqd", "IQD", 368, 3);
  ("Irr", "IRR", 364, 2);
  ("Isk", "ISK", 352, 0);
  ("Jmd", "JMD", 388, 2);
  ("Jod", "JOD", 400, 3);
  ("Jpy", "JPY", 392, 0);
  ("Kes", "KES", 404, 2);
  ("Kgs", "KGS", 417, 2);
  ("Khr", "KHR", 116, 2);
  ("Kmf", "KMF", 174, 0);
  ("Kpw", "KPW", 408, 2);
  ("Krw", "KRW", 410, 0);
  ("Kwd", "KWD", 414, 3);
  ("Kyd", "KYD", 136, 2);
  ("Kzt", "KZT", 398, 2);
  ("Lak", "LAK", 418, 2);
  ("Lbp", "LBP", 422, 2);
  ("Lkr", "LKR", 144, 2);
  ("Lrd", "LRD", 430, 2);
  ("Lsl", "LSL", 426, 2);
  ("Lyd", "LYD", 434, 3);
  ("Mad", "MAD", 504, 2);
  ("Mdl", "MDL", 498, 2);
  ("Mga", "MGA", 969, 2);
  ("Mkd", "MKD", 807, 2);
  ("Mmk", "MMK", 104, 2);
  ("Mnt", "MNT", 496, 2);
  ("Mop", "MOP", 446, 2);
  ("Mru", "MRU", 929, 2);
  ("Mur", "MUR", 480, 2);
  ("Mvr", "MVR", 462, 2);
  ("Mwk", "MWK", 454, 2);
  ("Mxn", "MXN", 484, 2);
  ("Myr", "MYR", 458, 2);
  ("Mzn", "MZN", 943, 2);
  ("Nad", "NAD", 516, 2);
  ("Ngn", "NGN", 566, 2);
  ("Nio", "NIO", 558, 2);
  ("Nok", "NOK", 578, 2);
  ("Npr", "NPR", 524, 2);
  ("Nzd", "NZD", 554, 2);
  ("Omr", "OMR", 512, 3);
  ("Pab", "PAB", 590, 2);
  ("Pen", "PEN", 604, 2);
  ("Pgk", "PGK", 598, 2);
  ("Php", "PHP", 608, 2);
  ("Pkr", "PKR", 586, 2);
  ("Pln", "PLN", 985, 2);
  ("Pyg", "PYG", 600, 0);
  ("Qar", "QAR", 634, 2);
  ("Ron", "RON", 946, 2);
  ("Rsd", "RSD", 941, 2);
  ("Rub", "RUB", 643, 2);
  ("Rwf", "RWF", 646, 0);
  ("Sar", "SAR", 682, 2);
  ("Sbd", "SBD", 90, 2);
  ("Scr", "SCR", 690, 2);
  ("Sdg", "SDG", 938, 2);
  ("Sek", "SEK", 752, 2);
  ("Sgd", "SGD", 702, 2);
  ("Shp", "SHP", 654, 2);
  ("Sle", "SLE", 925, 2);
  ("Sos", "SOS", 706, 2);
  ("Srd", "SRD", 968, 2);
  ("Ssp", "SSP", 728, 2);
  ("Stn", "STN", 930, 2);
  ("Svc", "SVC", 222, 2);
  ("Syp", "SYP", 760, 2);
  ("Szl", "SZL", 748, 2);
  ("Thb", "THB", 764, 2);
  ("Tjs", "TJS", 972, 2);
  ("Tmt", "TMT", 934, 2);
  ("Tnd", "TND", 788, 3);
  ("Top", "TOP", 776, 2);
  ("Try", "TRY", 949, 2);
  ("Ttd", "TTD", 780, 2);
  ("Twd", "TWD", 901, 2);
  ("Tzs", "TZS", 834, 2);
  ("Uah", "UAH", 980, 2);
  ("Ugx", "UGX", 800, 0);
  ("Usd", "USD", 840, 2);
  ("Uyu", "UYU", 858, 2);
  ("Uzs", "UZS", 860, 2);
  ("Ves", "VES", 928, 2);
  ("Vnd", "VND", 704, 0);
  ("Vuv", "VUV", 548, 0);
  ("Wst", "WST", 882, 2);
  ("Xaf", "XAF", 950, 0);
  ("Xcd", "XCD", 951, 2);
  ("Xof", "XOF", 952, 0);
  ("Xpf", "XPF", 953, 0);
  ("Yer", "YER", 886, 2);
  ("Zar", "ZAR", 710, 2);
  ("Zmw", "ZMW", 967, 2);
  ("Zwg", "ZWG", 924, 2);
]

let ctor_names : string list =
  List.map (fun (c, _, _, _) -> c) currencies

let iso_of_ctor (c : string) : string option =
  List.find_map
    (fun (c', iso, _, _) -> if c' = c then Some iso else None)
    currencies

(** Per-currency Money constructor names: Money.usd, Money.eur, ... *)
let money_ctor_names : string list =
  List.map
    (fun (_, iso, _, _) -> "Money." ^ String.lowercase_ascii iso)
    currencies
