module Api.TodoApi exposing
    ( ForAll
    , ForAllValues
    , ForAllKeys
    , UserId
    , userIdDecoder
    , userIdEncoder
    , ValidPort
    , validPortFieldDecoder
    , Authenticated
    , authenticatedFieldDecoder
    , TitleSafe
    , titleSafeFieldDecoder
    , titleSafe
    , LengthLessThan30
    , lengthLessThan30FieldDecoder
    , lengthLessThan30
    , ContainsAnA
    , containsAnAFieldDecoder
    , containsAnA
    , TodoId
    , todoIdFieldDecoder
    , todoId
    , IsOpen
    , isOpenFieldDecoder
    , Status(..)
    , statusDecoder
    , statusEncoder
    , Status2(..)
    , status2Decoder
    , status2Encoder
    , User
    , userDecoder
    , userEncoder
    , NewTodo
    , newTodoDecoder
    , newTodoEncoder
    , Todo
    , todoDecoder
    , postListTest
    , postTodos
    , getTodosMine
    , getTodosMineOpen
    , getTodos
    , putTodosComplete
    , TodoServerHumanAction(..)
    , TodoServerHumanActionRequest
    , todoServerHumanActionRequestDecoder
    )
{- Generated by tesl generate elm from todo-api.tesl — experimental client generation, do not edit by hand -}

import Http
import Json.Decode as D
import Json.Encode as E
import RefinementProofs.Theory exposing (Proven, axiom, exorcise, And, and)


type ForAll p
    = ForAll

type ForAllValues p
    = ForAllValues

type ForAllKeys p
    = ForAllKeys

-- ---------------------------------------------------------------------------
-- Newtypes
-- ---------------------------------------------------------------------------

type alias UserId =
    String

userIdDecoder : D.Decoder UserId
userIdDecoder =
    D.string

userIdEncoder : UserId -> E.Value
userIdEncoder value =
    E.string value

-- ---------------------------------------------------------------------------
-- Facts
-- ---------------------------------------------------------------------------

type ValidPort
    = ValidPort

validPortFieldDecoder : D.Decoder (Proven Int ValidPort)
validPortFieldDecoder =
    D.int
        |> D.map (axiom ValidPort)

type Authenticated
    = Authenticated

authenticatedFieldDecoder : D.Decoder (Proven User Authenticated)
authenticatedFieldDecoder =
    userDecoder
        |> D.map (axiom Authenticated)

type TitleSafe
    = TitleSafe

titleSafe : String -> Maybe (Proven String TitleSafe)
titleSafe input =
    if String.length input >= 4 && String.length input <= 120 then
        Just (axiom TitleSafe input)
    else
        Nothing

titleSafeFieldDecoder : D.Decoder (Proven String TitleSafe)
titleSafeFieldDecoder =
    D.string
        |> D.andThen
            (\v ->
                case titleSafe v of
                    Just x ->
                        D.succeed x
                    Nothing ->
                        D.fail "Failed proof: TitleSafe"
            )

type LengthLessThan30
    = LengthLessThan30

lengthLessThan30 : String -> Maybe (Proven String LengthLessThan30)
lengthLessThan30 input =
    if String.length input < 30 then
        Just (axiom LengthLessThan30 input)
    else
        Nothing

lengthLessThan30FieldDecoder : D.Decoder (Proven String LengthLessThan30)
lengthLessThan30FieldDecoder =
    D.string
        |> D.andThen
            (\v ->
                case lengthLessThan30 v of
                    Just x ->
                        D.succeed x
                    Nothing ->
                        D.fail "Failed proof: LengthLessThan30"
            )

type ContainsAnA
    = ContainsAnA

containsAnA : String -> Maybe (Proven String ContainsAnA)
containsAnA input =
    if String.contains "a" input then
        Just (axiom ContainsAnA input)
    else
        Nothing

containsAnAFieldDecoder : D.Decoder (Proven String ContainsAnA)
containsAnAFieldDecoder =
    D.string
        |> D.andThen
            (\v ->
                case containsAnA v of
                    Just x ->
                        D.succeed x
                    Nothing ->
                        D.fail "Failed proof: ContainsAnA"
            )

type TodoId
    = TodoId

todoId : String -> Maybe (Proven String TodoId)
todoId input =
    if String.startsWith "todo-" input && String.length input > 5 then
        Just (axiom TodoId input)
    else
        Nothing

todoIdFieldDecoder : D.Decoder (Proven String TodoId)
todoIdFieldDecoder =
    D.string
        |> D.andThen
            (\v ->
                case todoId v of
                    Just x ->
                        D.succeed x
                    Nothing ->
                        D.fail "Failed proof: TodoId"
            )

type IsOpen
    = IsOpen

isOpenFieldDecoder : D.Decoder (Proven Todo IsOpen)
isOpenFieldDecoder =
    todoDecoder
        |> D.map (axiom IsOpen)

-- ---------------------------------------------------------------------------
-- ADTs
-- ---------------------------------------------------------------------------

type Status
    = Open
    | Done

statusDecoder : D.Decoder Status
statusDecoder =
    D.field "tag" D.string
        |> D.andThen
            (\tag ->
                case tag of
                    "Open" ->
                        D.succeed Open

                    "Done" ->
                        D.succeed Done

                    _ ->
                        D.fail ("Unknown Status tag: " ++ tag)
            )

statusEncoder : Status -> E.Value
statusEncoder value =
    case value of
        Open ->
            E.object [ ( "tag", E.string "Open" ) ]
        Done ->
            E.object [ ( "tag", E.string "Done" ) ]

type Status2
    = Opened Int
    | Finished String

status2Decoder : D.Decoder Status2
status2Decoder =
    D.field "tag" D.string
        |> D.andThen
            (\tag ->
                case tag of
                    "Opened" ->
                        D.map Opened (D.field "value" D.int)

                    "Finished" ->
                        D.map Finished (D.field "value" D.string)

                    _ ->
                        D.fail ("Unknown Status2 tag: " ++ tag)
            )

status2Encoder : Status2 -> E.Value
status2Encoder value =
    case value of
        Opened f0 ->
            E.object [ ( "tag", E.string "Opened" ), ( "value", E.int f0 ) ]
        Finished f0 ->
            E.object [ ( "tag", E.string "Finished" ), ( "value", E.string f0 ) ]

-- ---------------------------------------------------------------------------
-- Human actions (agent → human handoff)
-- ---------------------------------------------------------------------------

type TodoServerHumanAction
    = TodoServerListTest D.Value
    | TodoServerCreateTodo D.Value
    | TodoServerListMyTodos D.Value
    | TodoServerListOpenTodos D.Value
    | TodoServerGetTodo D.Value
    | TodoServerCompleteTodo D.Value

type alias TodoServerHumanActionRequest =
    { handle : String
    , action : TodoServerHumanAction
    }

todoServerHumanActionRequestDecoder : D.Decoder TodoServerHumanActionRequest
todoServerHumanActionRequestDecoder =
    D.map2 TodoServerHumanActionRequest
        (D.field "handle" D.string)
        (D.field "action" D.string
            |> D.andThen
                (\tag ->
                    case tag of
                        "listTest" ->
                            D.map TodoServerListTest (D.field "args" D.value)

                        "createTodo" ->
                            D.map TodoServerCreateTodo (D.field "args" D.value)

                        "listMyTodos" ->
                            D.map TodoServerListMyTodos (D.field "args" D.value)

                        "listOpenTodos" ->
                            D.map TodoServerListOpenTodos (D.field "args" D.value)

                        "getTodo" ->
                            D.map TodoServerGetTodo (D.field "args" D.value)

                        "completeTodo" ->
                            D.map TodoServerCompleteTodo (D.field "args" D.value)

                        _ ->
                            D.fail ("Unknown TodoServer human action: " ++ tag)
                )
        )

-- ---------------------------------------------------------------------------
-- Records
-- ---------------------------------------------------------------------------

type alias User =
    { id : UserId
    , role : String
    }

userDecoder : D.Decoder User
userDecoder =
    D.map2 User
        (D.field "id" userIdDecoder)
        (D.field "role" D.string)

userEncoder : User -> E.Value
userEncoder rec =
    E.object
        [ ( "id", userIdEncoder rec.id )
        , ( "role", E.string rec.role )
        ]

type alias NewTodo =
    { title : Proven String (And (And TitleSafe LengthLessThan30) ContainsAnA)
    }

newTodoDecoder : D.Decoder NewTodo
newTodoDecoder =
    D.map NewTodo
        (D.field "title" (D.string
        |> D.andThen
            (\v ->
                case titleSafe v of
                    Just _ ->
                        case lengthLessThan30 v of
                            Just _ ->
                                case containsAnA v of
                                    Just _ ->
                                        D.succeed (axiom (and (and (TitleSafe) (LengthLessThan30)) (ContainsAnA)) v)
                                    Nothing ->
                                        D.fail "Failed proof: ContainsAnA"
                            Nothing ->
                                D.fail "Failed proof: LengthLessThan30"
                    Nothing ->
                        D.fail "Failed proof: TitleSafe"
            )))

newTodoEncoder : NewTodo -> E.Value
newTodoEncoder rec =
    E.object
        [ ( "title", E.string (exorcise rec.title) )
        ]

-- ---------------------------------------------------------------------------
-- Entity types (server-sourced)
-- ---------------------------------------------------------------------------

type alias Todo =
    { id : String
    , title : String
    , ownerId : UserId
    , status : Status
    , createdAt : Int
    }

todoDecoder : D.Decoder Todo
todoDecoder =
    D.map5 Todo
        (D.field "id" D.string)
        (D.field "title" D.string)
        (D.field "ownerId" userIdDecoder)
        (D.field "status" statusDecoder)
        (D.field "createdAt" (D.oneOf [ D.int, D.field "epochMillis" D.int ]))

-- ---------------------------------------------------------------------------
-- API
-- ---------------------------------------------------------------------------

postListTest : List ((Proven String TodoId)) -> (Result Http.Error String -> msg) -> Cmd msg
postListTest newTodos toMsg =
    Http.post
        { url = "/" ++ "list-test"
        , body = Http.jsonBody ((E.list (\value -> E.string (exorcise value))) newTodos)
        , expect = Http.expectJson toMsg D.string
        }

postTodos : NewTodo -> (Result Http.Error Todo -> msg) -> Cmd msg
postTodos newTodo toMsg =
    Http.post
        { url = "/" ++ "todos"
        , body = Http.jsonBody (newTodoEncoder newTodo)
        , expect = Http.expectJson toMsg todoDecoder
        }

getTodosMine : (Result Http.Error (List Todo) -> msg) -> Cmd msg
getTodosMine toMsg =
    Http.get
        { url = "/" ++ "todos" ++ "/" ++ "mine"
        , expect = Http.expectJson toMsg (D.list todoDecoder)
        }

getTodosMineOpen : (Result Http.Error (List (Proven Todo IsOpen)) -> msg) -> Cmd msg
getTodosMineOpen toMsg =
    Http.get
        { url = "/" ++ "todos" ++ "/" ++ "mine" ++ "/" ++ "open"
        , expect = Http.expectJson toMsg (D.list isOpenFieldDecoder)
        }

getTodos : Proven String TodoId -> (Result Http.Error Todo -> msg) -> Cmd msg
getTodos todoIdArg toMsg =
    Http.get
        { url = "/" ++ "todos" ++ "/" ++ exorcise todoIdArg
        , expect = Http.expectJson toMsg todoDecoder
        }

putTodosComplete : Proven String TodoId -> (Result Http.Error Todo -> msg) -> Cmd msg
putTodosComplete todoIdArg toMsg =
    Http.request
        { method = "PUT"
        , headers = []
        , url = "/" ++ "todos" ++ "/" ++ exorcise todoIdArg ++ "/" ++ "complete"
        , body = Http.emptyBody
        , expect = Http.expectJson toMsg todoDecoder
        , timeout = Nothing
        , tracker = Nothing
        }

