#!/usr/bin/env python3
"""Regenerate the Go unit constructors/accessors for Tesl.Units.

A unit's CONVERSION FACTOR is the one thing about a dimensioned quantity that is not in the
type system: the compiler's units catalog is factor-independent, and the checked-in Go table is
the runtime source of truth for conversion factors.  The generator reads that table and rewrites
the generated file, keeping regeneration independent of the removed runtime.

The affine constructors (Celsius, Fahrenheit) and the polymorphic operations are NOT generated:
they are written by hand in runtime/go/teslrt/units.go, because an offset is not a factor.

Regenerate (and commit) when a factor changes:

    python3 scripts/gen-go-units.py
"""

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "runtime" / "go" / "teslrt" / "units_data.go"
OUT_GO = ROOT / "runtime" / "go" / "teslrt" / "units_data.go"

LINE = re.compile(
    r"^func ([A-Za-z][A-Za-z0-9]*)\((value|quantity) float64\) float64\s+"
    r"\{ return (value|quantity) ([*/]) ([0-9.eE+\-]+) \}"
)


def main() -> None:
    out = [
        "package teslrt",
        "",
        "// Generated by scripts/gen-go-units.py from this Go conversion table.",
        "// DO NOT EDIT BY HAND — regenerate and commit when a conversion factor changes.",
        "//",
        "// A dimensioned quantity ERASES to a plain float64: the dimension lives in the",
        "// compiler's type layer, so every function here is ordinary arithmetic. A CONSTRUCTOR",
        "// converts a value in the named unit to the SI-canonical magnitude (meters, kilograms,",
        "// seconds, …); an ACCESSOR converts back.",
        "",
    ]
    count = 0
    for line in SOURCE.read_text().splitlines():
        match = LINE.match(line.strip())
        if not match:
            continue
        name, parameter, _return_parameter, operator, factor = match.groups()
        out.append(f"func {name}({parameter} float64) float64 {{ return {parameter} {operator} {factor} }}")
        count += 1
    out.append("")
    OUT_GO.write_text("\n".join(out))
    subprocess.run(["gofmt", "-w", str(OUT_GO)], check=True)
    print(f"wrote {OUT_GO} ({count} conversions)")


if __name__ == "__main__":
    main()
