#!/usr/bin/env python3
"""Generate the Go unit constructors/accessors for Tesl.Units from tesl/units.rkt.

A unit's CONVERSION FACTOR is the one thing about a dimensioned quantity that is not in the
type system: the compiler's units catalog is factor-independent, and `tesl/units.rkt` is where
the numbers live.  Copying them into the Go runtime by hand would be a second source of truth
for exactly the values a physical conversion cannot get wrong, so they are generated from the
Racket file instead — every `defunit`/`defaccessor` line becomes one Go function.

The affine constructors (Celsius, Fahrenheit) and the polymorphic operations are NOT generated:
they are written by hand in runtime/go/teslrt/units.go, because an offset is not a factor.

Regenerate (and commit) when a factor changes:

    python3 scripts/gen-go-units.py
"""

import re
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tesl" / "units.rkt"
OUT_GO = ROOT / "runtime" / "go" / "teslrt" / "units_data.go"

LINE = re.compile(r"^\((defunit|defaccessor)\s+\|([A-Za-z]+)\.([A-Za-z0-9]+)\|\s+(\S+)\)")


def go_factor(literal: str) -> str:
    """Render a Racket factor as a Go float64 literal.

    `#i1000/3600` is an inexact rational — Racket evaluates it to the nearest float64, and the
    Go literal has to be that same value rather than a rounded decimal, or a conversion would
    differ in the last bit.
    """
    if literal.startswith("#i"):
        value = float(Fraction(literal[2:]))
        return repr(value)
    return literal


def go_name(dimension: str, unit: str) -> str:
    return dimension + unit[0].upper() + unit[1:]


def main() -> None:
    out = [
        "package teslrt",
        "",
        "// Generated by scripts/gen-go-units.py from tesl/units.rkt.",
        "// DO NOT EDIT BY HAND — regenerate and commit when a conversion factor changes.",
        "//",
        "// A dimensioned quantity ERASES to a plain float64: the dimension lives in the",
        "// compiler's type layer, so every function here is ordinary arithmetic. A CONSTRUCTOR",
        "// converts a value in the named unit to the SI-canonical magnitude (meters, kilograms,",
        "// seconds, …); an ACCESSOR converts back. The factors are the Racket runtime's, read",
        "// from the file that owns them.",
        "",
    ]
    count = 0
    for line in SOURCE.read_text().splitlines():
        match = LINE.match(line.strip())
        if not match:
            continue
        kind, dimension, unit, factor = match.groups()
        name = go_name(dimension, unit)
        body = "value * " + go_factor(factor) if kind == "defunit" else "quantity / " + go_factor(factor)
        parameter = "value" if kind == "defunit" else "quantity"
        out.append(f"func {name}({parameter} float64) float64 {{ return {body} }}")
        count += 1
    out.append("")
    OUT_GO.write_text("\n".join(out))
    print(f"wrote {OUT_GO} ({count} conversions)")


if __name__ == "__main__":
    main()
