#!/usr/bin/env python3
"""Generate compiler/lib/tz_zones.ml from the system IANA zoneinfo tree.

The Tesl `TimeZone` surface is a FIXED set of constructors (no zone-name
strings — a typo is a compile error, and completion lists every zone), one per
canonical IANA zone from zone1970.tab, plus `Utc` and `FixedOffset`.  This
script bakes the (constructor name, IANA name) table the compiler uses for
typing, exports, and lowering; the runtime resolves the IANA name against the
system tzdata (dsl/private/tzif.rkt), and tests/timezone-zones-test.rkt is the
seam that every baked zone actually resolves there.

Regenerate (and commit the result) when tzdata adds a zone:

    python3 scripts/gen-tz-zones.py [path/to/zoneinfo]
"""

import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZONEINFO = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/usr/share/zoneinfo")
OUT = ROOT / "compiler" / "lib" / "tz_zones.ml"

# The standard Area/Location naming scheme.  Links (Europe/Stockholm →
# Europe/Berlin, etc.) are deliberately INCLUDED — they are the familiar names —
# while the legacy aliases (W-SU, GB-Eire, EST5EDT, Etc/*, …) are excluded.
AREAS = {"Africa", "America", "Antarctica", "Arctic", "Asia", "Atlantic",
         "Australia", "Europe", "Indian", "Pacific"}


def ctor_of(iana: str) -> str:
    # "America/Argentina/Buenos_Aires" -> "AmericaArgentinaBuenosAires"
    # "America/Port-au-Prince"         -> "AmericaPortAuPrince"
    parts = re.split(r"[/_\-]", iana)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def main() -> None:
    zones = []
    for f in ZONEINFO.rglob("*"):
        if not f.is_file():
            continue
        rel = f.relative_to(ZONEINFO).as_posix()
        if rel.split("/")[0] not in AREAS:
            continue
        with open(f, "rb") as fh:
            if fh.read(4) != b"TZif":
                continue
        zones.append(rel)
    zones = sorted(set(zones))

    ctors = {}
    for z in zones:
        c = ctor_of(z)
        if c in ctors:
            raise SystemExit(f"constructor collision: {c} for {ctors[c]} and {z}")
        ctors[c] = z

    lines = [
        "(* Generated by scripts/gen-tz-zones.py from zone1970.tab (tzdata).",
        "   DO NOT EDIT BY HAND — regenerate and commit when tzdata changes.",
        f"   {len(zones)} canonical zones. *)",
        "",
        "(** (constructor name, IANA zone name) — the fixed `TimeZone` zone set. *)",
        "let zones : (string * string) list = [",
    ]
    for c, z in sorted(ctors.items()):
        lines.append(f'  ("{c}", "{z}");')
    lines.append("]")
    lines.append("")
    lines.append("let iana_of_ctor (c : string) : string option = List.assoc_opt c zones")
    lines.append("")
    lines.append("let ctor_names : string list = List.map fst zones")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(zones)} zones)")


if __name__ == "__main__":
    main()
