(** Standalone reference for the embedded-docs generator.

    The authoritative generator is compiler/gen/gen_docs.ml, which is compiled
    as a dune executable and run automatically on every `dune build` via the
    rule in compiler/lib/dune.  You do not need to run this script manually.

    This script is kept as a fallback for environments without dune (e.g. a
    quick check outside the build tree):
      ocaml scripts/gen_embedded_docs.ml [repo-root]

    Key format:
      "manual/<file>.md"                  → manual section files
      "example/<file>.tesl"               → top-level examples
      "example/learn/<lesson>.tesl"       → lesson files
      "example/learn/<lesson>.md"         → lesson prose docs
      "example/kanel/<module>.tesl"       → kanel multi-module example
      "<root>.md"                         → top-level docs (LANGUAGE-SPEC.md etc.)
*)

let () =
  let repo_root =
    if Array.length Sys.argv > 1 then Sys.argv.(1)
    else Filename.dirname (Filename.dirname Sys.argv.(0))
  in

  let emit oc key path =
    (try
       let content = In_channel.with_open_text path In_channel.input_all in
       Printf.fprintf oc "  (%S,\n   %S);\n\n" key content
     with Sys_error _ -> ())
  in

  let oc = stdout in

  Printf.fprintf oc
    "(** Embedded documentation and examples — auto-generated.\n\
     \n\
     Generated by: ocaml scripts/gen_embedded_docs.ml\n\
     Do not edit directly; regenerate with: make gen-docs\n\
     (or: ocaml scripts/gen_embedded_docs.ml > compiler/lib/embedded_docs.ml)\n\
     *)\n\n";

  Printf.fprintf oc "let files : (string * string) list = [\n\n";

  (* Root-level documentation files *)
  List.iter (fun f ->
    let path = Filename.concat repo_root f in
    emit oc f path
  ) [ "LANGUAGE-SPEC.md"; "TESL.md"; "README.md"; "INSTALL.md" ];

  (* Manual directory *)
  let manual_dir = Filename.concat repo_root "manual" in
  if Sys.file_exists manual_dir then begin
    let files = Sys.readdir manual_dir |> Array.to_list |> List.sort String.compare in
    List.iter (fun f ->
      if Filename.check_suffix f ".md" then
        emit oc ("manual/" ^ f) (Filename.concat manual_dir f)
    ) files;

    (* dev-docs subdirectory *)
    let dev_dir = Filename.concat manual_dir "dev-docs" in
    if Sys.file_exists dev_dir then begin
      let dev_files = Sys.readdir dev_dir |> Array.to_list |> List.sort String.compare in
      List.iter (fun f ->
        if Filename.check_suffix f ".md" then
          emit oc ("manual/dev-docs/" ^ f) (Filename.concat dev_dir f)
      ) dev_files
    end
  end;

  (* Top-level example files (single-file examples) *)
  let example_dir = Filename.concat repo_root "example" in
  if Sys.file_exists example_dir then begin
    let files = Sys.readdir example_dir |> Array.to_list |> List.sort String.compare in
    List.iter (fun f ->
      if Filename.check_suffix f ".tesl" then
        emit oc ("example/" ^ f) (Filename.concat example_dir f)
    ) files;

    (* example/learn — lesson files *)
    let learn_dir = Filename.concat example_dir "learn" in
    if Sys.file_exists learn_dir then begin
      let learn_files = Sys.readdir learn_dir |> Array.to_list |> List.sort String.compare in
      List.iter (fun f ->
        if Filename.check_suffix f ".tesl" || Filename.check_suffix f ".md" then
          emit oc ("example/learn/" ^ f) (Filename.concat learn_dir f)
      ) learn_files
    end;

    (* example/kanel — multi-module SaaS example *)
    let kanel_dir = Filename.concat example_dir "kanel" in
    if Sys.file_exists kanel_dir then begin
      let kanel_files = Sys.readdir kanel_dir |> Array.to_list |> List.sort String.compare in
      List.iter (fun f ->
        if Filename.check_suffix f ".tesl" then
          emit oc ("example/kanel/" ^ f) (Filename.concat kanel_dir f)
      ) kanel_files
    end;

    (* example/chat *)
    let chat_dir = Filename.concat example_dir "chat" in
    if Sys.file_exists chat_dir then begin
      let chat_files = Sys.readdir chat_dir |> Array.to_list |> List.sort String.compare in
      List.iter (fun f ->
        if Filename.check_suffix f ".tesl" then
          emit oc ("example/chat/" ^ f) (Filename.concat chat_dir f)
      ) chat_files
    end;

    (* example/medical-journal_wip *)
    let med_dir = Filename.concat example_dir "medical-journal_wip" in
    if Sys.file_exists med_dir then begin
      let med_files = Sys.readdir med_dir |> Array.to_list |> List.sort String.compare in
      List.iter (fun f ->
        if Filename.check_suffix f ".tesl" then
          emit oc ("example/medical-journal_wip/" ^ f) (Filename.concat med_dir f)
      ) med_files
    end
  end;

  Printf.fprintf oc "]\n\n";
  Printf.fprintf oc "let lookup (key : string) : string option =\n";
  Printf.fprintf oc "  List.assoc_opt key files\n\n";
  Printf.fprintf oc "(** Lookup by filename only (basename), for convenient single-file access. *)\n";
  Printf.fprintf oc "let lookup_by_basename (name : string) : string option =\n";
  Printf.fprintf oc "  match List.find_opt (fun (k, _) -> Filename.basename k = name) files with\n";
  Printf.fprintf oc "  | Some (_, v) -> Some v\n";
  Printf.fprintf oc "  | None -> None\n\n";
  Printf.fprintf oc "(** All keys available in the embedded store. *)\n";
  Printf.fprintf oc "let all_keys () : string list = List.map fst files\n"
