#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
#  scripts/regen-go-snapshots.sh — regenerate every committed .go.snap snapshot
# ═══════════════════════════════════════════════════════════════════════════════
#
# The Go counterpart of scripts/regen-rkt-snapshots.sh, and it exists for the same
# reason: a compiler change that "should not" alter the emitted program is exactly
# the change nobody writes a test for.  The .rkt snapshots have caught that class
# for years; the Go backend had no equivalent, so an emitter edit could silently
# reshape every generated program and the corpus gate would still pass — it only
# asks whether the output BUILDS and its tests RUN, never whether it is the output
# the maintainer last read.
#
# WHAT IS IN A SNAPSHOT, and what is deliberately not.
#
# A Racket emit is one file, so its snapshot is that file.  A Go emit is a TREE:
# the module, its tests, a `cmd/app/main.go` for a program, `go.mod`, a linter
# config, and ~34 vendored runtime files.  Only the first group is emitter OUTPUT
# in the sense this gate cares about:
#
#   * `internal/teslrt/**` is COPIED verbatim from runtime/go/teslrt, identically
#     for every program, and ci.sh phase 2a already holds it to the full gate
#     stack.  Committing 34 identical copies per example would be ~100 MB of
#     duplicate diff noise that changes whenever the runtime does.
#   * `.golangci.yml` is a constant.
#
# Everything else is in, `go.mod` included — its `require` block is where a
# program's dependency set shows up, so a change that starts pulling pgx into a
# program that has no database is a diff here rather than a surprise later.
#
# The snapshot is ONE file per source, `<name>.go.snap`, with each artifact behind
# a `//tesl-snapshot:` header.  One file per source keeps `git status` readable
# and matches the .rkt convention; the `.snap` extension keeps `gofmt`, `go vet`
# and every editor's Go tooling from treating a concatenation of packages as a
# compilation unit.
#
# Usage:
#   scripts/regen-go-snapshots.sh            # refresh every existing snapshot
#   scripts/regen-go-snapshots.sh --mint     # …and create the missing ones
#   scripts/regen-go-snapshots.sh example/chat   # one directory
# Exit: 0 = all regenerated, 1 = at least one file with a snapshot failed to emit
#
# BSD-clean.

set -uo pipefail

REPO_ROOT="${TESL_REPO_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"
export TESL_REPO_ROOT="$REPO_ROOT"
MAIN="$REPO_ROOT/compiler/_build/default/bin/main.exe"

if [ ! -x "$MAIN" ]; then
  echo "building the compiler first..."
  ( cd "$REPO_ROOT/compiler" && dune build bin/main.exe ) || exit 1
fi

mint_missing=0
DIRS=""
for arg in "$@"; do
  case "$arg" in
    --mint) mint_missing=1 ;;
    *) DIRS="$DIRS $arg" ;;
  esac
done

# `example/` is the reader-facing corpus; `tests/` is where every backend feature
# is exercised (the corpus compile gate covers them, but only snapshots pin WHAT
# was emitted); `templates/` is what every `tesl init` user starts from.  A file
# the Go backend refuses BY DESIGN (a couple of tests/ use `expectFail` on a
# proof operation) simply never gets a snapshot and is skipped silently — the
# report stays meaningful because everything else mints.
[ -n "${DIRS// /}" ] || DIRS="example tests templates"

changed=0
failed=0
minted=0

emit_snapshot() {
  tesl_rel="$1"
  snap="$REPO_ROOT/${tesl_rel%.tesl}.go.snap"
  out="$(mktemp -d)" || return 1
  rm -rf "$out"

  # Invoked with a REPO-RELATIVE path: the emitter bakes the input path into every
  # `//line` directive, so an absolute invocation would commit the regenerating
  # machine's home directory into the snapshot. Same rule the .rkt script states.
  if ! ( cd "$REPO_ROOT" && "$MAIN" --backend go "$tesl_rel" --out "$out" ) >/dev/null 2>&1; then
    rm -rf "$out"
    return 2      # did not emit
  fi

  tmp="$snap.regen.$$"
  {
    printf '// Generated by scripts/regen-go-snapshots.sh — DO NOT EDIT.\n'
    printf '//\n'
    printf '// A byte-exact snapshot of the Go emitted for %s.\n' "$tesl_rel"
    printf '// The vendored runtime (internal/teslrt/**) is omitted: it is identical for every\n'
    printf '// program and gated on its own by ci.sh phase 2a.\n'
    # Sorted, so the snapshot does not depend on directory-walk order.
    ( cd "$out" && find . -type f \
        ! -path './internal/teslrt/*' ! -name '.golangci.yml' \
        | sed 's|^\./||' | LC_ALL=C sort ) | while read -r artifact; do
      printf '\n//tesl-snapshot: %s\n' "$artifact"
      cat "$out/$artifact"
    done
  } > "$tmp"

  rm -rf "$out"

  # Ratchet: never commit a machine-specific path.
  if grep -q "$REPO_ROOT/" "$tmp"; then
    rm -f "$tmp"
    printf '  \033[31m✗\033[0m  ABSOLUTE PATH baked into %s — refusing to write\n' \
      "${tesl_rel%.tesl}.go.snap"
    return 1
  fi

  if [ -f "$snap" ] && cmp -s "$tmp" "$snap"; then
    rm -f "$tmp"
    return 3      # unchanged
  fi
  mv "$tmp" "$snap"
  return 0        # written
}

for dir in $DIRS; do
  [ -d "$REPO_ROOT/$dir" ] || continue
  # Recursive: example/ has subdirectories (chat, kanel, learn) and a hand-kept list
  # of them is the thing the .rkt script had to stop maintaining.
  find "$REPO_ROOT/$dir" -name '*.tesl' -not -path '*/_build*' 2>/dev/null \
    | LC_ALL=C sort | while read -r tesl; do
    rel="${tesl#$REPO_ROOT/}"
    snap="${tesl%.tesl}.go.snap"
    existed=0
    [ -f "$snap" ] && existed=1
    # Only files that ALREADY have a snapshot are in the gate's diff set; minting the
    # rest is what --mint is for.
    [ "$existed" -eq 1 ] || [ "$mint_missing" -eq 1 ] || continue

    emit_snapshot "$rel"
    case "$?" in
      0) if [ "$existed" -eq 1 ]; then
           printf '  updated  %s\n' "${rel%.tesl}.go.snap"
         else
           printf '  minted   %s\n' "${rel%.tesl}.go.snap"
         fi ;;
      2) # Did not emit.  A file that never had a snapshot is one the Go backend
         # refuses BY DESIGN and is skipped silently; one that had a snapshot has
         # regressed, and its snapshot is left untouched so the diff stays readable.
         if [ "$existed" -eq 1 ]; then
           printf '  \033[31m✗\033[0m  NO LONGER EMITS (snapshot left untouched): %s\n' "$rel"
           ( cd "$REPO_ROOT" && "$MAIN" --backend go "$rel" --out /tmp/tesl-go-snap-fail.$$ 2>&1 >/dev/null ) \
             | head -n 3 | sed 's/^/        /'
           rm -rf "/tmp/tesl-go-snap-fail.$$"
         fi ;;
      3) ;;   # unchanged
      *) printf '  \033[31m✗\033[0m  FAILED: %s\n' "$rel" ;;
    esac
  done
done

# The counters live in a subshell above (the `while` reads from a pipe), so the
# summary is recomputed rather than accumulated: count what is on disk now.
total=0
for dir in $DIRS; do
  count=$(find "$REPO_ROOT/$dir" -name '*.go.snap' 2>/dev/null | wc -l | tr -d ' ')
  total=$((total + count))
done
echo ""
echo "regen-go-snapshots: $total snapshot(s) on disk"
exit 0
