module Api.KanelModels exposing
    ( ValidOrgId
    , validOrgId
    , ValidProjectId
    , validProjectId
    , ValidIssueId
    , validIssueId
    , ValidInvoiceId
    , validInvoiceId
    , ValidUserId
    , validUserId
    , OrgRole(..)
    , IssueStatus(..)
    , InvoiceStatus(..)
    , NotifyPayload
    , notifyPayloadEncoder
    , notifyPayloadDecoder
    , NewOrgRequest
    , newOrgRequestEncoder
    , newOrgRequestDecoder
    , NewProjectRequest
    , newProjectRequestEncoder
    , newProjectRequestDecoder
    , NewIssueRequest
    , newIssueRequestEncoder
    , newIssueRequestDecoder
    , UpdateIssueRequest
    , updateIssueRequestEncoder
    , updateIssueRequestDecoder
    , UpdateStatusRequest
    , updateStatusRequestEncoder
    , updateStatusRequestDecoder
    , NewCommentRequest
    , newCommentRequestEncoder
    , newCommentRequestDecoder
    , NewTimeEntryRequest
    , newTimeEntryRequestEncoder
    , newTimeEntryRequestDecoder
    , NewInvoiceRequest
    , newInvoiceRequestEncoder
    , newInvoiceRequestDecoder
    , KanelUser
    , kanelUserDecoder
    , Org
    , orgDecoder
    , OrgMembership
    , orgMembershipDecoder
    , Project
    , projectDecoder
    , ProjectMembership
    , projectMembershipDecoder
    , Issue
    , issueDecoder
    , IssueComment
    , issueCommentDecoder
    , TimeEntry
    , timeEntryDecoder
    , Invoice
    , invoiceDecoder
    )

{- Generated by tesl generate elm from KanelModels.tesl — do not edit by hand. -}

import Http
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode
import RefinementProofs.Theory exposing (Proven, axiom, exorcise)


-- ---------------------------------------------------------------------------
-- Facts (opaque types with smart constructors)
-- ---------------------------------------------------------------------------

{-| Fact: ValidOrgId
Validated by `checkOrgId`: length < 3
Only constructable via the smart constructor below.
-}
type ValidOrgId
    = ValidOrgId

validOrgId : String -> Maybe (Proven String ValidOrgId)
validOrgId input =
    if String.length input < 3 then
        Just (axiom ValidOrgId input)
    else
        Nothing

validOrgIdFieldDecoder : Decoder (Proven String ValidOrgId)
validOrgIdFieldDecoder =
    Decode.string
        |> Decode.andThen
            (\v ->
                case validOrgId v of
                    Just x ->
                        Decode.succeed x
                    Nothing ->
                        Decode.fail "Failed proof: ValidOrgId"
            )

{-| Fact: ValidProjectId
Validated by `checkProjectId`: length < 3
Only constructable via the smart constructor below.
-}
type ValidProjectId
    = ValidProjectId

validProjectId : String -> Maybe (Proven String ValidProjectId)
validProjectId input =
    if String.length input < 3 then
        Just (axiom ValidProjectId input)
    else
        Nothing

validProjectIdFieldDecoder : Decoder (Proven String ValidProjectId)
validProjectIdFieldDecoder =
    Decode.string
        |> Decode.andThen
            (\v ->
                case validProjectId v of
                    Just x ->
                        Decode.succeed x
                    Nothing ->
                        Decode.fail "Failed proof: ValidProjectId"
            )

{-| Fact: ValidIssueId
Validated by `checkIssueId`: length < 3
Only constructable via the smart constructor below.
-}
type ValidIssueId
    = ValidIssueId

validIssueId : String -> Maybe (Proven String ValidIssueId)
validIssueId input =
    if String.length input < 3 then
        Just (axiom ValidIssueId input)
    else
        Nothing

validIssueIdFieldDecoder : Decoder (Proven String ValidIssueId)
validIssueIdFieldDecoder =
    Decode.string
        |> Decode.andThen
            (\v ->
                case validIssueId v of
                    Just x ->
                        Decode.succeed x
                    Nothing ->
                        Decode.fail "Failed proof: ValidIssueId"
            )

{-| Fact: ValidInvoiceId
Validated by `checkInvoiceId`: length < 3
Only constructable via the smart constructor below.
-}
type ValidInvoiceId
    = ValidInvoiceId

validInvoiceId : String -> Maybe (Proven String ValidInvoiceId)
validInvoiceId input =
    if String.length input < 3 then
        Just (axiom ValidInvoiceId input)
    else
        Nothing

validInvoiceIdFieldDecoder : Decoder (Proven String ValidInvoiceId)
validInvoiceIdFieldDecoder =
    Decode.string
        |> Decode.andThen
            (\v ->
                case validInvoiceId v of
                    Just x ->
                        Decode.succeed x
                    Nothing ->
                        Decode.fail "Failed proof: ValidInvoiceId"
            )

{-| Fact: ValidUserId
Validated by `checkTargetUserId`: length < 3
Only constructable via the smart constructor below.
-}
type ValidUserId
    = ValidUserId

validUserId : String -> Maybe (Proven String ValidUserId)
validUserId input =
    if String.length input < 3 then
        Just (axiom ValidUserId input)
    else
        Nothing

validUserIdFieldDecoder : Decoder (Proven String ValidUserId)
validUserIdFieldDecoder =
    Decode.string
        |> Decode.andThen
            (\v ->
                case validUserId v of
                    Just x ->
                        Decode.succeed x
                    Nothing ->
                        Decode.fail "Failed proof: ValidUserId"
            )


-- ---------------------------------------------------------------------------
-- ADTs
-- ---------------------------------------------------------------------------

type OrgRole
    = RoleAdmin
    | RoleMember
    | RoleViewer

orgRoleDecoder : Decoder OrgRole
orgRoleDecoder =
    Decode.field "tag" Decode.string
        |> Decode.andThen
            (\tag ->
                case tag of
                    "RoleAdmin" ->
                        Decode.succeed RoleAdmin

                    "RoleMember" ->
                        Decode.succeed RoleMember

                    "RoleViewer" ->
                        Decode.succeed RoleViewer

                    _ ->
                        Decode.fail ("Unknown OrgRole tag: " ++ tag)
            )

orgRoleEncoder : OrgRole -> Encode.Value
orgRoleEncoder value =
    case value of
        RoleAdmin ->
            Encode.object [ ( "tag", Encode.string "RoleAdmin" ) ]
        RoleMember ->
            Encode.object [ ( "tag", Encode.string "RoleMember" ) ]
        RoleViewer ->
            Encode.object [ ( "tag", Encode.string "RoleViewer" ) ]

type IssueStatus
    = Backlog
    | Todo
    | InProgress
    | InReview
    | Done
    | Cancelled

issueStatusDecoder : Decoder IssueStatus
issueStatusDecoder =
    Decode.field "tag" Decode.string
        |> Decode.andThen
            (\tag ->
                case tag of
                    "Backlog" ->
                        Decode.succeed Backlog

                    "Todo" ->
                        Decode.succeed Todo

                    "InProgress" ->
                        Decode.succeed InProgress

                    "InReview" ->
                        Decode.succeed InReview

                    "Done" ->
                        Decode.succeed Done

                    "Cancelled" ->
                        Decode.succeed Cancelled

                    _ ->
                        Decode.fail ("Unknown IssueStatus tag: " ++ tag)
            )

issueStatusEncoder : IssueStatus -> Encode.Value
issueStatusEncoder value =
    case value of
        Backlog ->
            Encode.object [ ( "tag", Encode.string "Backlog" ) ]
        Todo ->
            Encode.object [ ( "tag", Encode.string "Todo" ) ]
        InProgress ->
            Encode.object [ ( "tag", Encode.string "InProgress" ) ]
        InReview ->
            Encode.object [ ( "tag", Encode.string "InReview" ) ]
        Done ->
            Encode.object [ ( "tag", Encode.string "Done" ) ]
        Cancelled ->
            Encode.object [ ( "tag", Encode.string "Cancelled" ) ]

type InvoiceStatus
    = Draft
    | Approved
    | Sent
    | Paid
    | Overdue

invoiceStatusDecoder : Decoder InvoiceStatus
invoiceStatusDecoder =
    Decode.field "tag" Decode.string
        |> Decode.andThen
            (\tag ->
                case tag of
                    "Draft" ->
                        Decode.succeed Draft

                    "Approved" ->
                        Decode.succeed Approved

                    "Sent" ->
                        Decode.succeed Sent

                    "Paid" ->
                        Decode.succeed Paid

                    "Overdue" ->
                        Decode.succeed Overdue

                    _ ->
                        Decode.fail ("Unknown InvoiceStatus tag: " ++ tag)
            )

invoiceStatusEncoder : InvoiceStatus -> Encode.Value
invoiceStatusEncoder value =
    case value of
        Draft ->
            Encode.object [ ( "tag", Encode.string "Draft" ) ]
        Approved ->
            Encode.object [ ( "tag", Encode.string "Approved" ) ]
        Sent ->
            Encode.object [ ( "tag", Encode.string "Sent" ) ]
        Paid ->
            Encode.object [ ( "tag", Encode.string "Paid" ) ]
        Overdue ->
            Encode.object [ ( "tag", Encode.string "Overdue" ) ]


-- ---------------------------------------------------------------------------
-- Records
-- ---------------------------------------------------------------------------

type alias NotifyPayload =
    { recipientEmail : String
    , subject : String
    , body : String
    }

notifyPayloadDecoder : Decoder NotifyPayload
notifyPayloadDecoder =
    Decode.map3 NotifyPayload
        (Decode.field "recipientEmail" Decode.string)
        (Decode.field "subject" Decode.string)
        (Decode.field "body" Decode.string)

notifyPayloadEncoder : NotifyPayload -> Encode.Value
notifyPayloadEncoder rec =
    Encode.object
        [
          ( "recipientEmail", Encode.string rec.recipientEmail )
                , ( "subject", Encode.string rec.subject )
                , ( "body", Encode.string rec.body )
        ]

type alias NewOrgRequest =
    { name : String
    , slug : String
    }

newOrgRequestDecoder : Decoder NewOrgRequest
newOrgRequestDecoder =
    Decode.map2 NewOrgRequest
        (Decode.field "name" Decode.string)
        (Decode.field "slug" Decode.string)

newOrgRequestEncoder : NewOrgRequest -> Encode.Value
newOrgRequestEncoder rec =
    Encode.object
        [
          ( "name", Encode.string rec.name )
                , ( "slug", Encode.string rec.slug )
        ]

type alias NewProjectRequest =
    { name : String
    , description : String
    }

newProjectRequestDecoder : Decoder NewProjectRequest
newProjectRequestDecoder =
    Decode.map2 NewProjectRequest
        (Decode.field "name" Decode.string)
        (Decode.field "description" Decode.string)

newProjectRequestEncoder : NewProjectRequest -> Encode.Value
newProjectRequestEncoder rec =
    Encode.object
        [
          ( "name", Encode.string rec.name )
                , ( "description", Encode.string rec.description )
        ]

type alias NewIssueRequest =
    { title : String
    , description : String
    , estimate : Int
    }

newIssueRequestDecoder : Decoder NewIssueRequest
newIssueRequestDecoder =
    Decode.map3 NewIssueRequest
        (Decode.field "title" Decode.string)
        (Decode.field "description" Decode.string)
        (Decode.field "estimate" Decode.int)

newIssueRequestEncoder : NewIssueRequest -> Encode.Value
newIssueRequestEncoder rec =
    Encode.object
        [
          ( "title", Encode.string rec.title )
                , ( "description", Encode.string rec.description )
                , ( "estimate", Encode.int rec.estimate )
        ]

type alias UpdateIssueRequest =
    { title : String
    , description : String
    , estimate : Int
    , assigneeId : String
    }

updateIssueRequestDecoder : Decoder UpdateIssueRequest
updateIssueRequestDecoder =
    Decode.map4 UpdateIssueRequest
        (Decode.field "title" Decode.string)
        (Decode.field "description" Decode.string)
        (Decode.field "estimate" Decode.int)
        (Decode.field "assigneeId" Decode.string)

updateIssueRequestEncoder : UpdateIssueRequest -> Encode.Value
updateIssueRequestEncoder rec =
    Encode.object
        [
          ( "title", Encode.string rec.title )
                , ( "description", Encode.string rec.description )
                , ( "estimate", Encode.int rec.estimate )
                , ( "assigneeId", Encode.string rec.assigneeId )
        ]

type alias UpdateStatusRequest =
    { newStatus : IssueStatus
    }

updateStatusRequestDecoder : Decoder UpdateStatusRequest
updateStatusRequestDecoder =
    Decode.map UpdateStatusRequest
        (Decode.field "newStatus" issueStatusDecoder)

updateStatusRequestEncoder : UpdateStatusRequest -> Encode.Value
updateStatusRequestEncoder rec =
    Encode.object
        [
          ( "newStatus", issueStatusEncoder rec.newStatus )
        ]

type alias NewCommentRequest =
    { body : String
    }

newCommentRequestDecoder : Decoder NewCommentRequest
newCommentRequestDecoder =
    Decode.map NewCommentRequest
        (Decode.field "body" Decode.string)

newCommentRequestEncoder : NewCommentRequest -> Encode.Value
newCommentRequestEncoder rec =
    Encode.object
        [
          ( "body", Encode.string rec.body )
        ]

type alias NewTimeEntryRequest =
    { minutes : Int
    , description : String
    }

newTimeEntryRequestDecoder : Decoder NewTimeEntryRequest
newTimeEntryRequestDecoder =
    Decode.map2 NewTimeEntryRequest
        (Decode.field "minutes" Decode.int)
        (Decode.field "description" Decode.string)

newTimeEntryRequestEncoder : NewTimeEntryRequest -> Encode.Value
newTimeEntryRequestEncoder rec =
    Encode.object
        [
          ( "minutes", Encode.int rec.minutes )
                , ( "description", Encode.string rec.description )
        ]

type alias NewInvoiceRequest =
    { notes : String
    }

newInvoiceRequestDecoder : Decoder NewInvoiceRequest
newInvoiceRequestDecoder =
    Decode.map NewInvoiceRequest
        (Decode.field "notes" Decode.string)

newInvoiceRequestEncoder : NewInvoiceRequest -> Encode.Value
newInvoiceRequestEncoder rec =
    Encode.object
        [
          ( "notes", Encode.string rec.notes )
        ]


-- ---------------------------------------------------------------------------
-- Entity types (server-sourced, trusted from DB)
-- ---------------------------------------------------------------------------

type alias KanelUser =
    { id : String
    , email : String
    , passwordHash : String
    , displayName : String
    , createdAt : Int
    }

kanelUserDecoder : Decoder KanelUser
kanelUserDecoder =
    Decode.map5 KanelUser
        (Decode.field "id" Decode.string)
        (Decode.field "email" Decode.string)
        (Decode.field "passwordHash" Decode.string)
        (Decode.field "displayName" Decode.string)
        (Decode.field "createdAt" Decode.int)

type alias Org =
    { id : String
    , name : String
    , slug : String
    , createdAt : Int
    }

orgDecoder : Decoder Org
orgDecoder =
    Decode.map4 Org
        (Decode.field "id" Decode.string)
        (Decode.field "name" Decode.string)
        (Decode.field "slug" Decode.string)
        (Decode.field "createdAt" Decode.int)

type alias OrgMembership =
    { id : String
    , orgId : String
    , userId : String
    , role : OrgRole
    , joinedAt : Int
    }

orgMembershipDecoder : Decoder OrgMembership
orgMembershipDecoder =
    Decode.map5 OrgMembership
        (Decode.field "id" Decode.string)
        (Decode.field "orgId" Decode.string)
        (Decode.field "userId" Decode.string)
        (Decode.field "role" orgRoleDecoder)
        (Decode.field "joinedAt" Decode.int)

type alias Project =
    { id : String
    , orgId : String
    , name : String
    , description : String
    , archived : Bool
    , createdAt : Int
    }

projectDecoder : Decoder Project
projectDecoder =
    Decode.map6 Project
        (Decode.field "id" Decode.string)
        (Decode.field "orgId" Decode.string)
        (Decode.field "name" Decode.string)
        (Decode.field "description" Decode.string)
        (Decode.field "archived" Decode.bool)
        (Decode.field "createdAt" Decode.int)

type alias ProjectMembership =
    { id : String
    , projectId : String
    , userId : String
    , joinedAt : Int
    }

projectMembershipDecoder : Decoder ProjectMembership
projectMembershipDecoder =
    Decode.map4 ProjectMembership
        (Decode.field "id" Decode.string)
        (Decode.field "projectId" Decode.string)
        (Decode.field "userId" Decode.string)
        (Decode.field "joinedAt" Decode.int)

type alias Issue =
    { id : String
    , projectId : String
    , orgId : String
    , title : String
    , description : String
    , status : IssueStatus
    , assigneeId : Maybe String
    , reporterId : String
    , estimate : Int
    , dueAt : Maybe Int
    , createdAt : Int
    , updatedAt : Int
    }

issueDecoder : Decoder Issue
issueDecoder =
    Decode.succeed Issue
        |> required "id" Decode.string
        |> required "projectId" Decode.string
        |> required "orgId" Decode.string
        |> required "title" Decode.string
        |> required "description" Decode.string
        |> required "status" issueStatusDecoder
        |> required "assigneeId" (decodeMaybe Decode.string)
        |> required "reporterId" Decode.string
        |> required "estimate" Decode.int
        |> required "dueAt" (decodeMaybe Decode.int)
        |> required "createdAt" Decode.int
        |> required "updatedAt" Decode.int

type alias IssueComment =
    { id : String
    , issueId : String
    , authorId : String
    , body : String
    , createdAt : Int
    }

issueCommentDecoder : Decoder IssueComment
issueCommentDecoder =
    Decode.map5 IssueComment
        (Decode.field "id" Decode.string)
        (Decode.field "issueId" Decode.string)
        (Decode.field "authorId" Decode.string)
        (Decode.field "body" Decode.string)
        (Decode.field "createdAt" Decode.int)

type alias TimeEntry =
    { id : String
    , issueId : String
    , userId : String
    , orgId : String
    , minutes : Int
    , description : String
    , invoiceId : String
    , loggedAt : Int
    }

timeEntryDecoder : Decoder TimeEntry
timeEntryDecoder =
    Decode.map8 TimeEntry
        (Decode.field "id" Decode.string)
        (Decode.field "issueId" Decode.string)
        (Decode.field "userId" Decode.string)
        (Decode.field "orgId" Decode.string)
        (Decode.field "minutes" Decode.int)
        (Decode.field "description" Decode.string)
        (Decode.field "invoiceId" Decode.string)
        (Decode.field "loggedAt" Decode.int)

type alias Invoice =
    { id : String
    , orgId : String
    , status : InvoiceStatus
    , totalMinutes : Int
    , notes : String
    , createdAt : Int
    , approvedAt : Int
    }

invoiceDecoder : Decoder Invoice
invoiceDecoder =
    Decode.map7 Invoice
        (Decode.field "id" Decode.string)
        (Decode.field "orgId" Decode.string)
        (Decode.field "status" invoiceStatusDecoder)
        (Decode.field "totalMinutes" Decode.int)
        (Decode.field "notes" Decode.string)
        (Decode.field "createdAt" Decode.int)
        (Decode.field "approvedAt" Decode.int)


-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------


required : String -> Decode.Decoder a -> Decode.Decoder (a -> b) -> Decode.Decoder b
required fieldName decoder pipeline =
    Decode.map2 (|>) (Decode.field fieldName decoder) pipeline


decodeMaybe : Decode.Decoder a -> Decode.Decoder (Maybe a)
decodeMaybe innerDecoder =
    Decode.field "tag" Decode.string
        |> Decode.andThen
            (\tag ->
                case tag of
                    "Nothing" ->
                        Decode.succeed Nothing

                    "Something" ->
                        Decode.field "fields" (Decode.field "value" innerDecoder)
                            |> Decode.map Just

                    _ ->
                        Decode.fail ("Unknown Maybe tag: " ++ tag)
            )


encodeMaybe : (a -> Encode.Value) -> Maybe a -> Encode.Value
encodeMaybe encodeInner maybeValue =
    case maybeValue of
        Nothing ->
            Encode.object [ ( "tag", Encode.string "Nothing" ) ]

        Just v ->
            Encode.object
                [ ( "tag", Encode.string "Something" )
                , ( "fields", Encode.object [ ( "value", encodeInner v ) ] )
                ]
