import { useEffect, useState } from "react";
// todo-api-client.ts is generated by: tesl generate ts todo-api.tesl
import {
  Todo,
  NewTodoSchema,
  TodoIdSchema,
  getTodosMine as listMyTodos,
  getTodosMineOpen as listMyOpenTodos,
  postTodos as createTodo,
  putTodosComplete as completeTodo,
  configure,
  // getTodos(todoId) — requires a branded TodoId, not a plain string.
  // Call TodoIdSchema.parse(rawId) first.
} from "./todo-api-client";

// Derived from the generated schema — stays in sync if constraints change.
const TitleSchema = NewTodoSchema.shape.title;

// Point the generated client at your backend
configure("http://localhost:8086");

// ---------------------------------------------------------------------------
// Cookie helpers — the API uses a plain `user` cookie for auth (dev only)
// ---------------------------------------------------------------------------

function getUserCookie(): string | null {
  const match = document.cookie.match(/(?:^|;\s*)user=([^;]+)/);
  return match ? decodeURIComponent(match[1]) : null;
}

function setUserCookie(userId: string) {
  document.cookie = `user=${encodeURIComponent(userId)}; path=/`;
}

// ---------------------------------------------------------------------------
// Styles (inline — no CSS framework needed for this demo)
// ---------------------------------------------------------------------------

const styles = {
  container: {
    maxWidth: 640,
    margin: "40px auto",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    color: "#1a1a1a",
    padding: "0 16px",
  } satisfies React.CSSProperties,
  heading: { fontSize: 24, fontWeight: 700, marginBottom: 4 } satisfies React.CSSProperties,
  subheading: {
    fontSize: 13,
    color: "#6b7280",
    marginBottom: 32,
  } satisfies React.CSSProperties,
  section: { marginBottom: 32 } satisfies React.CSSProperties,
  sectionTitle: {
    fontSize: 13,
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: "#6b7280",
    marginBottom: 12,
  },
  form: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    marginBottom: 8,
  } satisfies React.CSSProperties,
  input: {
    flex: 1,
    padding: "8px 12px",
    border: "1px solid #d1d5db",
    borderRadius: 6,
    fontSize: 14,
    outline: "none",
  } satisfies React.CSSProperties,
  inputError: {
    flex: 1,
    padding: "8px 12px",
    border: "1px solid #ef4444",
    borderRadius: 6,
    fontSize: 14,
    outline: "none",
  } satisfies React.CSSProperties,
  button: {
    padding: "8px 16px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 14,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  buttonSmall: {
    padding: "4px 10px",
    background: "#16a34a",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    fontSize: 12,
    cursor: "pointer",
  } satisfies React.CSSProperties,
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed" as const,
  },
  errorText: { color: "#ef4444", fontSize: 12, marginTop: 2 } satisfies React.CSSProperties,
  filterRow: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
  } satisfies React.CSSProperties,
  filterBtn: (active: boolean): React.CSSProperties => ({
    padding: "4px 12px",
    border: "1px solid #d1d5db",
    borderRadius: 20,
    fontSize: 13,
    cursor: "pointer",
    background: active ? "#2563eb" : "#fff",
    color: active ? "#fff" : "#374151",
  }),
  todoItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    marginBottom: 8,
    background: "#fff",
  } satisfies React.CSSProperties,
  todoTitle: (done: boolean): React.CSSProperties => ({
    fontSize: 14,
    textDecoration: done ? "line-through" : "none",
    color: done ? "#9ca3af" : "#111827",
  }),
  todoMeta: {
    fontSize: 11,
    color: "#9ca3af",
    marginTop: 2,
  } satisfies React.CSSProperties,
  badge: (done: boolean): React.CSSProperties => ({
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 12,
    background: done ? "#f3f4f6" : "#dcfce7",
    color: done ? "#6b7280" : "#16a34a",
    marginLeft: 8,
  }),
  errorBox: {
    padding: "10px 14px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 6,
    color: "#dc2626",
    fontSize: 13,
    marginBottom: 16,
  } satisfies React.CSSProperties,
  empty: {
    color: "#9ca3af",
    fontSize: 14,
    padding: "16px 0",
    textAlign: "center" as const,
  },
  note: {
    fontSize: 12,
    color: "#6b7280",
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: 6,
    padding: "8px 12px",
    marginTop: 16,
    fontFamily: "monospace",
    lineHeight: 1.6,
  } satisfies React.CSSProperties,
};

// ---------------------------------------------------------------------------
// TodoItem component
// ---------------------------------------------------------------------------

interface TodoItemProps {
  todo: Todo;
  onComplete: (todo: Todo) => void;
  completing: boolean;
}

function TodoItem({ todo, onComplete, completing }: TodoItemProps) {
  const done = todo.status.tag === "Done";
  return (
    <div style={styles.todoItem}>
      <div>
        <span style={styles.todoTitle(done)}>{todo.title}</span>
        <span style={styles.badge(done)}>{todo.status.tag}</span>
        <div style={styles.todoMeta}>
          {todo.id} · owner: {todo.ownerId}
        </div>
      </div>
      {!done && (
        <button
          style={
            completing
              ? { ...styles.buttonSmall, ...styles.buttonDisabled }
              : styles.buttonSmall
          }
          disabled={completing}
          onClick={() => onComplete(todo)}
        >
          {completing ? "…" : "Complete"}
        </button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// App component
// ---------------------------------------------------------------------------

type Filter = "all" | "open";

function LoginForm({ onLogin }: { onLogin: (id: string) => void }) {
  const [userInput, setUserInput] = useState("mikael");
  return (
    <div style={{ maxWidth: 360, margin: "80px auto", fontFamily: "'Segoe UI', system-ui, sans-serif", padding: "0 16px" }}>
      <h1 style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>Tesl Todo — dev login</h1>
      <p style={{ fontSize: 13, color: "#6b7280", marginBottom: 20 }}>
        Sets a <code>user</code> cookie (matches the <code>cookieAuth</code> handler in todo-api.tesl).
      </p>
      <form
        onSubmit={(e) => { e.preventDefault(); if (userInput.trim()) { setUserCookie(userInput.trim()); onLogin(userInput.trim()); } }}
        style={{ display: "flex", gap: 8 }}
      >
        <input
          autoFocus
          value={userInput}
          onChange={(e) => setUserInput(e.target.value)}
          placeholder="User ID"
          style={{ flex: 1, padding: "8px 12px", border: "1px solid #d1d5db", borderRadius: 6, fontSize: 14 }}
        />
        <button type="submit" style={{ padding: "8px 16px", background: "#2563eb", color: "#fff", border: "none", borderRadius: 6, fontSize: 14, cursor: "pointer" }}>
          Sign in
        </button>
      </form>
    </div>
  );
}

function TodoApp({ userId }: { userId: string }) {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [filter, setFilter] = useState<Filter>("open");
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);

  // New-todo form state
  const [titleInput, setTitleInput] = useState("");
  const [titleError, setTitleError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);

  // Completing state: track which todo id is being completed
  const [completingId, setCompletingId] = useState<string | null>(null);

  // Load todos based on filter
  useEffect(() => {
    setLoading(true);
    setFetchError(null);
    const fetcher = filter === "open" ? listMyOpenTodos : listMyTodos;
    fetcher()
      .then(setTodos)
      .catch((e: unknown) =>
        setFetchError(e instanceof Error ? e.message : String(e))
      )
      .finally(() => setLoading(false));
  }, [filter]);

  // ---------------------------------------------------------------------------
  // Validate title using the combined schema from NewTodoSchema.shape.title,
  // which enforces ALL proof constraints (TitleSafe && LengthLessThan30).
  // Client-side validation mirrors every `via` checker in the Tesl codec.
  // ---------------------------------------------------------------------------
  function handleTitleChange(value: string) {
    setTitleInput(value);
    if (value.length === 0) {
      setTitleError(null);
      return;
    }
    const result = TitleSchema.safeParse(value);
    setTitleError(result.success ? null : result.error.issues[0].message);
  }

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    setCreateError(null);

    // Parse with the combined TitleSchema to obtain a value satisfying all
    // proof constraints. If any constraint fails we never hit the API.
    const parsed = TitleSchema.safeParse(titleInput);
    if (!parsed.success) {
      setTitleError(parsed.error.issues[0].message);
      return;
    }

    // `parsed.data` satisfies every brand on NewTodo.title — type-checks.
    const newTodo = { title: parsed.data };

    setCreating(true);
    try {
      const created = await createTodo(newTodo);
      setTodos((prev) => [created, ...prev]);
      setTitleInput("");
      setTitleError(null);
    } catch (e: unknown) {
      setCreateError(e instanceof Error ? e.message : String(e));
    } finally {
      setCreating(false);
    }
  }

  async function handleComplete(todo: Todo) {
    // `todo.id` is typed as `string` from the server response schema.
    // We use TodoIdSchema.parse to obtain the branded TodoId that
    // completeTodo() requires — this validates the format locally before
    // sending the request.
    const todoId = TodoIdSchema.parse(todo.id);
    setCompletingId(todo.id);
    try {
      const updated = await completeTodo(todoId);
      setTodos((prev) => prev.map((t) => (t.id === updated.id ? updated : t)));
    } catch (e: unknown) {
      setFetchError(e instanceof Error ? e.message : String(e));
    } finally {
      setCompletingId(null);
    }
  }

  return (
    <div style={styles.container}>
      <h1 style={styles.heading}>Tesl Todo</h1>
      <p style={styles.subheading}>
        Signed in as <strong>{userId}</strong> ·{" "}
        TypeScript/Zod client — generated by{" "}
        <code>tesl generate ts todo-api.tesl</code>
      </p>

      {/* ------------------------------------------------------------------ */}
      {/* Create a new todo                                                   */}
      {/* ------------------------------------------------------------------ */}
      <div style={styles.section}>
        <div style={styles.sectionTitle}>New todo</div>
        <form onSubmit={handleCreate}>
          <div style={styles.form}>
            <input
              style={titleError ? styles.inputError : styles.input}
              placeholder="What needs doing?"
              value={titleInput}
              onChange={(e) => handleTitleChange(e.target.value)}
              disabled={creating}
            />
            <button
              type="submit"
              style={
                creating || !!titleError || titleInput.length === 0
                  ? { ...styles.button, ...styles.buttonDisabled }
                  : styles.button
              }
              disabled={creating || !!titleError || titleInput.length === 0}
            >
              {creating ? "Adding…" : "Add"}
            </button>
          </div>
          {/* Client-side TitleSafe validation — no API call needed */}
          {titleError && <div style={styles.errorText}>{titleError}</div>}
          {createError && <div style={styles.errorBox}>{createError}</div>}
        </form>
        <div style={styles.note}>
          {`// NewTodoSchema.shape.title.safeParse(titleInput) runs before fetch()`}
          <br />
          {`// Enforces all proof constraints: TitleSafe && LengthLessThan30`}
          <br />
          {`// createTodo({ title: parsed.data }) — title satisfies every brand`}
        </div>
      </div>

      {/* ------------------------------------------------------------------ */}
      {/* Todo list                                                           */}
      {/* ------------------------------------------------------------------ */}
      <div style={styles.section}>
        <div style={styles.sectionTitle}>Todos</div>

        <div style={styles.filterRow}>
          <button
            style={styles.filterBtn(filter === "open")}
            onClick={() => setFilter("open")}
          >
            Open
          </button>
          <button
            style={styles.filterBtn(filter === "all")}
            onClick={() => setFilter("all")}
          >
            All
          </button>
        </div>

        {fetchError && <div style={styles.errorBox}>{fetchError}</div>}

        {loading ? (
          <div style={styles.empty}>Loading…</div>
        ) : todos.length === 0 ? (
          <div style={styles.empty}>No todos yet.</div>
        ) : (
          todos.map((todo) => (
            <TodoItem
              key={todo.id}
              todo={todo}
              onComplete={handleComplete}
              completing={completingId === todo.id}
            />
          ))
        )}

        <div style={styles.note}>
          {`// completeTodo(todoId: TodoId) requires a branded TodoId`}
          <br />
          {`// TodoIdSchema.parse(todo.id) validates "todo-*" format client-side`}
          <br />
          {`// getTodo(todoId) — same requirement; plain string would be a type error`}
        </div>
      </div>
    </div>
  );
}

export default function App() {
  const [userId, setUserId] = useState<string | null>(getUserCookie);
  if (!userId) return <LoginForm onLogin={setUserId} />;
  return <TodoApp userId={userId} />;
}
