// Generated by tesl generate ts from todo-api.tesl — experimental client generation, do not edit by hand
// Module: TodoApi
import { z } from "zod";

// --- Newtypes ---

export const UserIdSchema = z.string().brand<"UserId">();
export type UserId = z.infer<typeof UserIdSchema>;

// --- Facts ---

// Fact: ValidPort — established by `validPort` (server-side only)
export type ValidPort = { readonly __tesl_valid_port: unique symbol };

// Fact: Authenticated — set by auth `cookieAuth` (server-side only)
export type Authenticated = { readonly __tesl_authenticated: unique symbol };

// Fact: TitleSafe — validated by `isSafeTitle`
export const TitleSafeSchema = z.string().min(4).max(120).brand<"TitleSafe">();
export type TitleSafe = z.infer<typeof TitleSafeSchema>;

// Fact: LengthLessThan30 — validated by `lengthLessThan30`
export const LengthLessThan30Schema = z.string().max(29).brand<"LengthLessThan30">();
export type LengthLessThan30 = z.infer<typeof LengthLessThan30Schema>;

// Fact: ContainsAnA — established by `containsAnA` (server-side only)
export type ContainsAnA = { readonly __tesl_contains_an_a: unique symbol };

// Fact: TodoId — validated by `isTodoId`
export const TodoIdSchema = z.string().startsWith("todo-").min(6).brand<"TodoId">();
export type TodoId = z.infer<typeof TodoIdSchema>;

// Fact: IsOpen — established by `checkOpen` (server-side only)
export type IsOpen = { readonly __tesl_is_open: unique symbol };


// --- ADTs ---

const _Status_OpenSchema = z.object({ tag: z.literal("Open") });
const _Status_DoneSchema = z.object({ tag: z.literal("Done") });
export const StatusSchema = z.discriminatedUnion("tag", [_Status_OpenSchema, _Status_DoneSchema]);
export type Status = z.infer<typeof StatusSchema>;

const _Status2_OpenedSchema = z.object({ tag: z.literal("Opened"), value: z.number().int() });
const _Status2_FinishedSchema = z.object({ tag: z.literal("Finished"), value: z.string() });
export const Status2Schema = z.discriminatedUnion("tag", [_Status2_OpenedSchema, _Status2_FinishedSchema]);
export type Status2 = z.infer<typeof Status2Schema>;


// --- Human actions (agent -> human handoff) ---

const _TodoServerHumanAction_listTestSchema = z.object({ action: z.literal("listTest"), handle: z.string(), args: z.unknown() });
const _TodoServerHumanAction_createTodoSchema = z.object({ action: z.literal("createTodo"), handle: z.string(), args: z.unknown() });
const _TodoServerHumanAction_listMyTodosSchema = z.object({ action: z.literal("listMyTodos"), handle: z.string(), args: z.unknown() });
const _TodoServerHumanAction_listOpenTodosSchema = z.object({ action: z.literal("listOpenTodos"), handle: z.string(), args: z.unknown() });
const _TodoServerHumanAction_getTodoSchema = z.object({ action: z.literal("getTodo"), handle: z.string(), args: z.unknown() });
const _TodoServerHumanAction_completeTodoSchema = z.object({ action: z.literal("completeTodo"), handle: z.string(), args: z.unknown() });
export const TodoServerHumanActionRequestSchema = z.discriminatedUnion("action", [_TodoServerHumanAction_listTestSchema, _TodoServerHumanAction_createTodoSchema, _TodoServerHumanAction_listMyTodosSchema, _TodoServerHumanAction_listOpenTodosSchema, _TodoServerHumanAction_getTodoSchema, _TodoServerHumanAction_completeTodoSchema]);
export type TodoServerHumanActionRequest = z.infer<typeof TodoServerHumanActionRequestSchema>;


// --- Records ---

export const UserSchema = z.object({
  id: UserIdSchema,
  role: z.string(),
});
export type User = z.infer<typeof UserSchema>;

export const NewTodoSchema = z.object({
  title: TitleSafeSchema.and(LengthLessThan30Schema),
});
export type NewTodo = z.infer<typeof NewTodoSchema>;


// --- Entity response types ---

export const TodoSchema = z.object({
  id: z.string(),
  title: z.string(),
  ownerId: UserIdSchema,
  status: StatusSchema,
  createdAt: z.union([z.number().int(), z.object({ epochMillis: z.number().int() }).transform((v) => v.epochMillis)]),
});
export type Todo = z.infer<typeof TodoSchema>;


// --- API client ---

let _teslBase = "";
export function configure(base: string): void { _teslBase = base; }

export async function postListTest(newTodos: Array<string>): Promise<string> {
  const res = await fetch(`${_teslBase}/list-test`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(newTodos),
  });
  if (!res.ok) throw new Error(`POST /list-test failed: ${res.status}`);
  return z.string().parse(await res.json()) as string;
}

export async function postTodos(newTodo: NewTodo): Promise<Todo> {
  const res = await fetch(`${_teslBase}/todos`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(newTodo),
  });
  if (!res.ok) throw new Error(`POST /todos failed: ${res.status}`);
  return TodoSchema.parse(await res.json()) as Todo;
}

export async function getTodosMine(): Promise<Array<Todo>> {
  const res = await fetch(`${_teslBase}/todos/mine`, {
    method: "GET",
    credentials: "include",
  });
  if (!res.ok) throw new Error(`GET /todos/mine failed: ${res.status}`);
  return z.array(TodoSchema).parse(await res.json()) as Array<Todo>;
}

export async function getTodosMineOpen(): Promise<Array<Todo>> {
  const res = await fetch(`${_teslBase}/todos/mine/open`, {
    method: "GET",
    credentials: "include",
  });
  if (!res.ok) throw new Error(`GET /todos/mine/open failed: ${res.status}`);
  return z.array(TodoSchema).parse(await res.json()) as Array<Todo>;
}

export async function getTodos(todoId: z.infer<typeof TodoIdSchema>): Promise<Todo> {
  const res = await fetch(`${_teslBase}/todos/${todoId}`, {
    method: "GET",
    credentials: "include",
  });
  if (!res.ok) throw new Error(`GET /todos/:todoId failed: ${res.status}`);
  return TodoSchema.parse(await res.json()) as Todo;
}

export async function putTodosComplete(todoId: z.infer<typeof TodoIdSchema>): Promise<Todo> {
  const res = await fetch(`${_teslBase}/todos/${todoId}/complete`, {
    method: "PUT",
    credentials: "include",
  });
  if (!res.ok) throw new Error(`PUT /todos/:todoId/complete failed: ${res.status}`);
  return TodoSchema.parse(await res.json()) as Todo;
}

